### ISSUE TITLE
localMSA.py

### ISSUE THREAD

**Issue by Mahmoudbassuoni** [ydLiu-HIT/Psi-caller#5]
now I am running the _localMSA.py_ script with the parallel option but it give me _list index out of range_ error 

**that was the error I got:** 

`Traceback (most recent call last):
  File "localMSA.py", line 644, in <module>
    run()
  File "localMSA.py", line 638, in run
    main_ctrl(args)
  File "localMSA.py", line 569, in main_ctrl
    most_likely_genotype([c], query, qual, args.mismatch2 if multiCan else args.mismatch, Sig)
  File "/home/ionadmin/Psi-caller-1.0.1/subCall.py", line 294, in most_likely_genotype
    likeliScore = realignToHaplotype(QUERY, QUAL, Haplot, var, x_score, Sig)
  File "/home/ionadmin/Psi-caller-1.0.1/subCall.py", line 276, in realignToHaplotype
    likeliScore = realignWithQuality(QUERY, QUAL, Haplot, var, Param, amplifier, extflank, x_score)
  File "/home/ionadmin/Psi-caller-1.0.1/subCall.py", line 242, in realignWithQuality
    qual = QUAL[m]
IndexError: list index out of range

gzip: stdout: Broken pipe`

what could be the issue here ?

**Comment by Mahmoudbassuoni** [comment]
Hi @ydLiu-HIT can you check that please ?

**Comment by Mahmoudbassuoni** [comment]
it was all about using `--useBaseQuality` flag,,,
